### PR TITLE
Chore: Import the WebUI into the main Datapane Repository

### PR DESCRIPTION
**Pull request by antdking**
This PR contains 2 main components;
- a rewritten history of datapane-next to be under the `webui/` directory (we don't allow merge commits)
- Minor alterations for building standalone from our build harness

---

Details for replicating the subtree import (without a merge commit):

Command for generating the prefixed tree:
```sh
git clone git@github.com:datapane/datapane-next.git -b master dp-next-scratch
cd dp-next-scratch
git filter-repo --to-subdirectory-filter webui
git remote add origin git@github.com:datapane/datapane-next.git
git push origin master:webui-master
```
The above is available here: https://github.com/datapane/datapane-next/tree/webui-master

Then from the `datapane` repo:
```sh
git remote add dpnext git@github.com:datapane/datapane-next.git
git checkout -b chore/new-branch-name dpnext/webui-master
git pull --rebase origin master
git push -u origin chore/new-branch-name
```
---

for open PRs in datapane-next, Ping me, and I'll work with you to rewrite the history ready

### CODE REVIEW

**Comment by Buroni** [comment]
General structure and commits all LGTM!

Just got a Q before we merge -- will there be a follow-up PR in the `datapane-hosted` repo to point to `datapane/webui/`? As the codebase is still using the old `datapane-next` submodule.

**Comment by antdking** [comment]
Ah ha, sorry I thought I had the draft PR up already: https://github.com/datapane/datapane-hosted/pull/929

**Review by Buroni — APPROVED** [review]

**Comment by antdking** [comment]
@Buroni I've just had to do a rebase, as we disallow merge commits.

Updating generation instructions atm

**Comment by antdking** [comment]
> We can enable merge commits temporarily to merge this if makes things easier

Too late, done the history rewrite!
It's more reflective of what's actually happened anyway; and the original repo will be archived, not deleted.

**Pull request merged**
