### PR TITLE
Change app operations to functions

### PR DESCRIPTION
**Pull request by Buroni**
## Prerequsites

- [x] Has been tested locally
- [ ] If a bugfix, have included a breaking test if possible

## Proposed Changes

- Update app operations to the format in the examples below. Underlying class model is the same, but the public API has been changed to function wrappers around these classes

```py
dp.upload(app, "app-name", open=True)
dp.serve(app, "app-name", dest="dest-folder", overwrite=True, open=True)
dp.save(app, "app-name.html", standalone=True, open=True)
dp.build(app, "app-name", overwrite=True)
```

### CODE REVIEW

**Comment by lanthias** [comment]
Looks great, thanks @Buroni, though it should be `save_report` if we are going for snake case.

**Comment by Buroni** [comment]
@lanthias Have renamed to `save_app` following the report -> app rename.

**Comment by lanthias** [comment]
Thanks, sorry I thought I shared context on Basecamp but I never hit "Comment"!

> The reason Report is suffixed is that the output will only ever be a snapshot generally. Functions will require deployment or serving; the idea of a Report is something we may talk about as a "Snapshot" of an app.

**Comment by Buroni** [comment]
Ohh okay so it should be `save_report` regardless of the rename I guess

**Comment by lanthias** [comment]
Yep exactly, as per above it should be `save_report` - because a single HTML rendering of a view is a report, as it can never have functions

**Review by mands — APPROVED** [review]
LGTM

**Pull request merged**
