### PR TITLE
MT Changes (Docs)

### PR DESCRIPTION
**Pull request by mands**
Thank you so much for contributing to Datapane, please help us by filing out this PR template and ensure you have read the [CONTRIBUTING.md](../CONTRIBUTING.md).

It may take a few days to review your PR and merge it - please bear with us!

Thanks!

fixes #

## Prerequsites

- [ ] Has been tested locally
- [ ] If a bugfix, have included a breaking test if possible

## Proposed Changes

- ...

### CODE REVIEW

**Review by shahinrostami — APPROVED** [review]
Looking great - just some minor pre-commit issues @ajgilmour.

Also, do we want to remove these?

```INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - tutorials/datapane-cloud/embedding.ipynb
              - tutorials/datapane-enterprise/authenticate-datapane.ipynb
              - tutorials/styling/adding-source-code.ipynb```



It would be great, maybe in a future PR, to get rid of the Explanations section by merging the Datapane Enterprise sections and relocating the support policy!

**Comment by mands** [comment]
@ajgilmour let's merge this today if possible, thanks!

**Comment by ajgilmour** [comment]
Sorry, just seeing this now. Fixing pre-commit issues, and will remove those unused pages.

**Comment by ajgilmour** [comment]
Just FYI, I decided to include
  - tutorials/datapane-enterprise/authenticate-datapane.ipynb
as it seemed like it might be useful. Removed the other two pages, though.

**Comment by ajgilmour** [comment]
@mands @shahinrostami This looks like it's good to go if we're all happy?

**Comment by mands** [comment]
Yep good with me!

**Comment by shahinrostami** [comment]
Excellent - all green! LGTM

**Pull request merged**
