### PR TITLE
Run all linters on all files each PR

### PR DESCRIPTION
**Pull request by spookylukey**
Otherwise, changes in linting config aren't tested, and quickly you end up with files that don't pass linting, but this is only
picked up the next time someone tries to edit the file.

Same as https://github.com/datapane/datapane-hosted/commit/b7248bd9ab91524fcc9755f8f972fb6e582fa07c for datapane-hosted

### CODE REVIEW

**Comment by spookylukey** [comment]
@Buroni This fix has exposed a few eslint errors (and lots of warnings, which we can ignore) - see https://github.com/datapane/datapane/runs/7808597548?check_suite_focus=true

I'm not sure how to best address these.
The flake8 errors I'm fixing in another branch.

**Comment by mands** [comment]
LGTM - happy to merge & run this in CI going forwards.

The linked GH action above seems to generate a lot of errors from the test modules - shall we disable type-checking for tests (I think it used to be at somepoint).

Whilst we're taking a quick look at this, is it possible to update the `autoflake` pre-commit step to be more verbose? I'm finding that it's changing my code but not giving enough insight into what it has changed (and maybe why?). This makes things quite tricky as you're never sure if it's changes have broken the code (by removing an import for instance that wasn't added to `__all__` during refactoring)

**Comment by spookylukey** [comment]
@mands The flake8 errors are fixed now, partly by silencing them for test files as you suggested, done in another branch. (There was some config intended to do that but it wasn't working). I'm completely in favour of silencing any errors/warnings that we aren't intending to do anything about - it's just noise that you have to wade through, and hides real issues.

The remaining 2 eslint errors in this branch need to be fixed before merging, to keep the test suite green. The warnings don't need to be addressed AFAICS.

**Comment by mands** [comment]
> The remaining 2 eslint errors in this branch need to be fixed before merging, to keep the test suite green. The warnings don't need to be addressed AFAICS.

@Buroni - would you be able to look at this? thanks

**Comment by Buroni** [comment]
I've made the following changes

- Fixed existing eslint errors
- Replaced deprecated `babel-eslint` with `@babel/eslint-parser` and update our other pre-commit dependencies, as we were hitting [this bug ](https://stackoverflow.com/questions/48391913/eslint-error-cannot-read-property-range-of-null)which exists on older eslint dependencies.
- Removed duplicate `dp-notebook/` dir which I must have missed when moving things over in the refactor

**Pull request merged**
