### PR TITLE
Remote storybook blocks

### PR DESCRIPTION
**Pull request by Buroni**
## Proposed Changes

- Create embeddable storybook components for each block type
- Update classnames in `BigNumber.vue` to make tailwind classnames explicit, so that tailwind doesn't shake them off during compilation.

## TODO

There's still some outstanding questions around how we handle relatively large resource files for some of our block types, see https://3.basecamp.com/5309418/buckets/27854429/messages/5078238845

### CODE REVIEW

**Review by mallok-s — APPROVED** [review]
Everything looks good to me. There's nothing in here I have any concerns about. I'm happy for this to go into master

**Review by mallok-s — COMMENTED** [review]
Actually sorry, I just noticed one the checks are failing. Is this a known issue? Or newly introduced?

**Comment by shahinrostami** [comment]
> @Buroni - is this PR still open or are we handling the "blockshub" page with a different approach now? I recall you mentioning something during the retreat

We're going to use MkDocs and mknotebooks for our BlocksHub, but I think @Buroni mentioned these storybook blocks will still be used elsewhere, e.g. notion

**Comment by Buroni** [comment]
The original motive was to allow storybook blocks to be embedded in notion as well as blockhub. @ajgilmour do you still intend to use this for notion embedding?

**Comment by ajgilmour** [comment]
> The original motive was to allow storybook blocks to be embedded in notion as well as blockhub. @ajgilmour do you still intend to use this for notion embedding? If so I'll rebase the PR and merge

I suppose having both wouldn't hurt! But only if it's not too much of a pain.

**Pull request merged**
