### PR TITLE
Rename report to app in Docs 

### PR DESCRIPTION
**Pull request by shahinrostami**
Thank you so much for contributing to Datapane, please help us by filing out this PR template and ensure you have read the [CONTRIBUTING.md](../CONTRIBUTING.md).

It may take a few days to review your PR and merge it - please bear with us!

Thanks!

## Prerequsites

- [x] Has been tested locally
- [ ] If a bugfix, have included a breaking test if possible

## Proposed Changes

- Switching out occurrences of "report" to "app" in text and code.
- Renaming files.
- Renaming pages and setting up redirects from the old ones. The `mkdocs-redirects` plugin only accepts `old` pages that end in `.md`, however, the redirects work regardless. E.g. `"tutorials/basics/create-a-report.md": "tutorials/basics/create-an-app.ipynb"`.
- Add PostHog snippet to every page.
- Rebuild all pages to update metadata. Note: the upcoming series of docs improvements will include a pre-commit hook that clears all outputs.
- Removed old Apps content

### CODE REVIEW

**Comment by lanthias** [comment]
Thanks @shahinrostami! I also picked up the piece of work around adding PostHog to the docs, but with a slightly different approach (it seems they recommend adding it as a custom analytics provider, which I've done in my branch.)

I also have some styling changes to fix inconsistencies and add our default colour scheme, and plan to do a general clean-up of the docs (i.e. to remove old enterprise stuff that doesn't make sense anymore.)

I'm wondering if I should branch off of this, in that case (my changes right now won't clash with yours, but if I make changes to the actual content it could be a bit of a hairy rebase)

**Comment by shahinrostami** [comment]
> Thanks @shahinrostami! I also picked up the piece of work around adding PostHog to the docs, but with a slightly different approach (it seems they recommend adding it as a custom analytics provider, which I've done in my branch.)
> 
> I also have some styling changes to fix inconsistencies and add our default colour scheme, and plan to do a general clean-up of the docs (i.e. to remove old enterprise stuff that doesn't make sense anymore.)
> 
> I'm wondering if I should branch off of this, in that case (my changes right now won't clash with yours, but if I make changes to the actual content it could be a bit of a hairy rebase)

Sounds great - Looking forward to the changes! 

I think that's a good idea - please branch off this one so we can avoid the mess 😅. Switching out my inclusion of the PostHog snippet [0] sent by James should be easy enough! 

I've also removed all the old "Apps" content as mentioned in the to-do.

If the changes look alright to you I can merge this in now so I don't hold you up 👍


[0] https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

**Comment by shahinrostami** [comment]
> @shahinrostami, sounds good - might be easier if you remove your PH snippet first in that case, and I'll rebase on master.

No problem @lanthias ! I've just pushed the commit that removes it. I've kept `extra.js` in-place for future JS snippets.

**Review by lanthias — APPROVED** [review]
LGTM!

**Pull request merged**
